### ISSUE TITLE
note level

### ISSUE THREAD

**Issue by eagleyesss** [opentoonz/opentoonz_nightlies#7]
why i cant type on the note level?

**Comment by RodneyBaker** [comment]
@eagleyesss We'll need more information to provide feedback.
I'll suggest joining one of the Opentoonz discords where you can chat, post screen grabs and otherwise get feedback in real time. That is one of the easiest ways to troubleshoot problems.

You've posted in a location that doesn't normally recieve questions so it is unlikely you'll get answers here anyway.

Link:  https://discord.gg/UQxvYBKW5U

**Comment by eagleyesss** [comment]
i did not hit enter .it works now thx

**Comment by RodneyBaker** [comment]
@eagleyesss  If you can close this report that will help as no admin/moderator type person generally visits this repository often.
